### PR TITLE
Structuring of REST API

### PR DESCRIPTION
**Pull request by byt3smith**
### FIR REST API
I began work on implementing a REST api for FIR using the Django REST Framework. So far you can get a list of users, groups, and incidents using GET verb, and you can use POST to /api/incidents to create a new event. 

This is just the beginning of the possibilities. I plan to add the ability to:
* Close incidents
* Trigger notifications to be sent using fir_alerting
* Download incident reports, etc..

Let me know if these are features you would also like to see added. If not I will keep them in my personal repository

### CODE REVIEW

**Comment by mrflibbleoz** [comment]
Would be very keen for some of these features. Particularly keen to see functionality where our incident alerting system (Splunk) can automatically generate incidents.

**Comment by byt3smith** [comment]
@mrflibbleoz That is my use case as well. I plan on building an alert action application that formats the data from Splunk specifically for creating incidents in FIR.

Here is a sampling of the POST data you would send with current configuration to generate a new incident.

```
{
    "date": "2015-11-10T14:01:00",
    "is_starred": false,
    "subject": "New Incident via API",
    "description": "This incident was generated through the API",
    "severity": 2,
    "category": 7,
    "detection": 4,
    "opened_by": 1,
    "is_incident": true
}
```

**Comment by vacmf** [comment]
I agree with all of you. Please don't be too specific to Splunk, and keep the API as open as possible. Today you never know what tool/service you'll need to integrate tomorrow.
Another point, as everyone is more and more often making use of Cyber Intel, I'd love to use the API to pull artifacts from cases and compare them automatically with Intel sources.

@byt3smith will you use an API key approach for authentication?

**Comment by byt3smith** [comment]
@vacmf The REST API will be able to be consumed by any REST client, I just meant I am also going to build a specific client for Splunk to interact with it. 

As for authentication, I am using the Django REST Framework with default settings, which utilizes Basic Authentication, so you can just use your username/password to authenticate (I would suggest creating a limited privilege user account for API access)

Here is how you would interact with the API using cURL:
```curl -H 'Accept: application/json; indent=4' -u admin:password http://<fir-instance>/api```

**Comment by byt3smith** [comment]
Also, I'm looking into the best way to open up the Artifacts to the API. I can see being able to:
* add artifacts to incidents 
* query for all incidents that have seen a specific artifact. 

Let me know of any other use cases you can think of and I'll see what I can do.

**Comment by sroberts** [comment]
Artifacts is by far the most interesting to me, as I've been thinking about integrating FIR with a tool like [defpoint/threat_note](https://github.com/defpoint/threat_note) for doing the threat intelligence portion.

**Comment by tomchop** [comment]
@byt3smith: Thanks a lot for this contribution! It was definitely on our roadmap so this will be of great help to us. We'll review it in the next few days; we're probably going to keep improving it so that we can map tokens to users and authenticate with that.

@sroberts: I'm building a FIR module to integrate the threat intel platform I'm currently working on (which will probably take big inputs from threat_note)... keep you posted on that soon.

**Comment by byt3smith** [comment]
@tomchop No problem. Added basic token-based auth in my latest commit. Tokens will be auto-generated for all new users.

You can also retrieve your token by POSTing to the ```/api/token``` route.
screen shot 2015-11-24 at 7 54 23 am

**Comment by lennartkoopmann** [comment]
I'd love to build an `AlarmCallback` plugin for [Graylog](https://www.graylog.org/) that can automatically create incidents based on patterns in log messages.

That should only take 1-2 hours of work but a REST API is different required. I'm happy to test this PR with it if you tell me that this still has a chance to be merged?

Thanks!

**Comment by gaelmuller** [comment]
Hello @lennartkoopmann. Sorry this pull request didn't get the love it deserved lately.

We are definitely planning to merge this one, but we would like for the API feature to be extracted as a plugin first. I will have a look at it this week.

Please go ahead and test this PR, and do not hesitate to share your feedback.

**Comment by gaelmuller** [comment]
This was merged in 26d962e8af6ab270181cfaca4f699f96d1544ff9 with some modifications:

  - Extracted as an optional plugin
  - Consistent access control
  - Removed Group API (not really of any use in FIR)
  - Changed Artifacts API to only support listing and retrieving, using artifact value instead of id
  - Consistent behavior for incident creation

**Comment by sroberts** [comment]
Giphy

I was just telling someone yesterday how excited I was for this PR to land. Awesome to see! I'm not crazy about the "you can figure out the API probably" but I'm happy to write a PR to document that. Excellent work! :sparkles:

**Comment by weslambert** [comment]
@byt3smith or @sroberts  -- Would you have any more documentation/examples of how you are currently using the REST API w/FIR to pull data back or post data (ex. simple client using powershell, etc)?  

I ultimately would like to have IDS alerts from another Linux machine auto-generate incidents in FIR, but I have no idea where to begin. 

Thanks,
Wes

**Comment by eth-0** [comment]
@weslambert. I've been meaning to document the API for a while now. I use it very extensively. I can pump this up on my priorities list.

**Comment by byt3smith** [comment]
@weslambert @eth-0 I know the core devs were talking about using Swagger to document the API, but there is no reason we shouldn't generate some simple docs in the meantime. It has been on my to do list to provide some API client examples, so I will focus on getting those pushed out here soon.

**Comment by eth-0** [comment]
@byt3smith Agreed. I was talking with @tomchop about the API documentation a while back and we had talked about giving Sphinx a try. But honestly, I'm willing to try anything. Just looking to help the project out because I use it heavily.

**Comment by weslambert** [comment]
Anything would be great and much appreciated!

**Comment by weslambert** [comment]
I just started using @byt3smith <https://github.com/byt3smith>'s
fir-powershell client (https://github.com/byt3smith/fir-powershell) and I
am able to successfully pull back info from the incidents, files, users,
and artifacts endpoints, however, I cannot figure out how to pull back
specific values, such as a user with an id of "1", or an incident with an
id of "100".  Could anyone offer any advice on how to structure an
appropriate query.  An example or two would be greatly appreciated.

Thanks!
Wes

**Comment by byt3smith** [comment]
@weslambert To pull down a specific example, you just add the ID of the object to the end of the URI. Example to pull back the incident with ID 1:

```
GET http://<fir-server>/api/incidents/1
```

When I have more time I will add more to the PowerShell client. I am working on a Golang client library as well.

**Comment by weslambert** [comment]
I can get this information if I do it through the browser, but am not able
to through the client (the remote server returned an error: (404) Not
Found.):


Ex. powershell -File fir_client.ps1 -u https://<fir-server> -t <token> -e
incidents/1


Is this the correct way to do this with the script?  TIA for your help!


Thanks,
Wes

**Pull request closed without merging**
