### PR TITLE
Basic python3 compatibility

### PR DESCRIPTION
**Pull request by SleuthKid**
Basic changes to the code base to fix obvious python3 compatibility issues.
To run FIR with py3, requirements.txt needs to be adjusted for flup (only dev version for py3) and wsgiref (included in py3) changes:

```
django>=1.9,<1.10
djangorestframework
markdown
django-filter
argparse==1.2.1
cssselect==0.9.1
flup==1.0.3.dev20151210
lxml==3.4.2
pymongo==2.8
pyquery==1.2.9
python-dateutil==2.4.1
pytz==2014.10
six==1.9.0
```

Let's push FIR to the future :)

### CODE REVIEW

**Comment by eth-0** [comment]
SleuthKid, when I ported the code to py3, I also had to replace `__unicode__` with `__str__` or else in the admin panel when editing the Incident Categories the drop down just said "Incident Category object" rather than the name of the category. Did you run into this as well?

**Comment by SleuthKid** [comment]
You are right. There are some further things that need to be changed. A good resource for porting things can be found here: https://docs.djangoproject.com/en/1.10/topics/python3/

As there was no reaction on this pull request I did not push it further.

**Comment by tomchop** [comment]
It's merge week! @SleuthKid, did you continue working on this or should we take over from here?

**Comment by SleuthKid** [comment]
@tomchop : as there was no reaction on my pull requests from the project I did no further work on it.

This pull requests can possibly be closed an ignored by now. Porting the whole project to py3 should probably be done in a consolidated effort.

**Comment by eth-0** [comment]
I was able to port our production instance of FIR over to python3 in about an hour. I'd love to help out on this if needed, @tomchop.

**Pull request closed without merging**
