### PR TITLE
Fixes and enhancements

### PR DESCRIPTION
**Pull request by jbaptperez**
This is a set of fixes and improvements mainly aimed at a better development experience.

Regards.

### CODE REVIEW

**Comment by Augustin-FL** [comment]
Hi
I was planning to have a look into this PR (You caught some interesting bugs..). May I ask why you closed it?

Can I take some of part of it and include them into FIR codebase?

**Comment by jbaptperez** [comment]
Hi @Augustin-FL,
I had to assert that I could submit the PR, which wasn't sure at the moment.
I opened a new PR (#303) with the same changes as I couldn't reopen this one.

**Comment by Augustin-FL** [comment]
Thank you !
I will have a look into it

**Comment by jbaptperez** [comment]
@Augustin-FL, can you completely delete the PR #303 which is an undesirable copy of the PR #304?

**Comment by Augustin-FL** [comment]
Hi,
Sadly, github allow repo owners to delete issues [but not PRs](https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github)

Please let me know when #304 is ready for merge

**Comment by jbaptperez** [comment]
@Augustin-FL, I'm used to deal with Git which allows to redo anything (rebase etc.).
This is not the case of GitHub (even on our own repositories, OMG), thank you for the information.

The PR #304 is ready to merge!

**Pull request closed without merging**
